### ISSUE TITLE
specifying field type for a nested field

### ISSUE THREAD

**Issue by searler** [arqex/react-json#2]
What is the syntax to specify types and settings for a field of an embedded object?

 For example
```
var doc = {
  user: "",
  password: "",
  nested : {
    kind : "A"
  }
};
```

How would one specify that the kind field is a select, with an array of options?

**Comment by arqex** [comment]
http://codepen.io/arqex/pen/jPgjYJ?editors=001

**Comment by searler** [comment]
Thanks for the quick response!

**Comment by arqex** [comment]
@searler The thing is that react-json is in an alpha stage, that is why there is no good docs and the API is prone to changes.

Creating the example I realized that it is more dev friendly to remove the settings property from the field descriptions. Instead of 
```
var settings = {
  fields: {
    nested: { type:'object', fields:{
     kind: {
       type: 'select',
       settings: { options:[ 'A', 'B', 'C'] }
     } 
    }}
  }
}
```

we'd do 
```
var settings = {
  fields: {
    nested: { type:'object', fields:{
     kind: {
       type: 'select',
       options:[ 'A', 'B', 'C']
     } 
    }}
  }
}
```

I think it is a big step forward in how to define the json-form

**Comment by jide** [comment]
This does not work for arrays does it ?
